title: Shailesh Patel
description: I am Data Science Entusiast with extensive experience of using advance technology in Data Science.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
